### ISSUE TITLE
I am integrating braintree gateway in my code, so ica

### ISSUE THREAD

**Issue by brajrajsingh11** [braintree/braintree_java#55]
### General information

I am integrating braintree gateway in my code, so i create maven project and add braintree dependency 2.46.0 in code, at compile time its not giving any issue but on time is giving following exception

* SDK/Library version:  2.46.0
* Environment:  Sandbox
* Language, language version, and OS:  Java 1.7.0_60 on window 7

### Issue description
```
Caused by: java.lang.ExceptionInInitializerError
	at com.braintreegateway.BraintreeGateway.<init>(BraintreeGateway.java:56)
	at com.bdbizviz.yujaa.services.impl.YujaaServicesImpl.<clinit>(YujaaServicesImpl.java:1516)
	at com.bdbizviz.yujaa.services.activator.YujaaServicesActivator.start(YujaaServicesActivator.java:19)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
	... 22 more
Caused by: java.lang.NullPointerException
```

**Comment by jaypatel512** [comment]
Hey @brajrajsingh11 !

Can you please use our latest version if possible [2.73.0](https://github.com/braintree/braintree_java/releases/tag/2.73.0) and see if you are still having this problem. Using the latest version is always recommended.

Let me know if you still face this issue.

**Comment by crookedneighbor** [comment]
I'm going to close this, but feel free to comment here if you're still having issues.
